name: Build MacOs

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: |
          xcodebuild CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
          tar -C build/Release -cf Radiola.app.tar Radiola.app

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Radiola.app.tar
          path: Radiola.app.tar
