name: Build MacOs

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: |
          echo "BUILD_DATE=$(date +%Y.%m.%d-%H.%M.%S)" >> $GITHUB_ENV

          xcodebuild CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
          
          tar -C build/Release -cf Radiola-${{ env.BUILD_DATE }}.tar Radiola.app
          cp ${{github.workspace}}/.github/workflows/makedmg.sh makedmg.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Radiola-${{ env.BUILD_DATE }}
          path: |
            Radiola-${{ env.BUILD_DATE }}.tar
            makedmg.sh
