name: Build MacOs

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: xcodebuild CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
